name: Auto-generate userscripts

on:
  push:
    branches: [ main ]
    paths:
      - "generate/**"
      - ".github/workflows/**"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}

    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      
    - name: "Run generate script"
      run: |
        chmod +x ./generate.sh
        ./generate.sh
      working-directory: generate

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
