name: Auto-generate userscripts

on:
  push:
    branches: [ main ]
    paths:
      - "generate/**"
      - ".github/workflows/**"

  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main    

    - name: "Auto-generate userscript"
      shell: bash
      run: |
        GITHUB_ACTOR_ID=${{ github.actor }}
        GITHUB_ACTOR=${{ github.repository_owner }}
        sudo bash ./generate-all.sh 2>&1
      working-directory: generate

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 1
